name: main build

on:
  push:
    branches:
      - main

jobs:
  deploy_scripts:
    runs-on: ubuntu-latest
    steps:
# check out the github repository
    - uses: actions/checkout@v4.1.6
# compress the scripts into a tar.xz archive
    - name: assemble
      run: |
        website="/tmp/website"
        mkdir -p $website
        cd ..
        ./scripts/linux/xzCompress.sh "$website/scripts" ./scripts/LICENSE ./scripts/README.md ./scripts/linux
        cd ./scripts
        rm -f .gitignore
        rm -rf .github
        rm -rf *.md
        cp -R linux "$website/"
# deploy to github pages
    - name: deploy scripts
      uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e
      with:
        branch: gh-pages
        folder: /tmp/website/
        single-commit: true
